name: activemq-image-builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build_container_images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update -qq
          sudo apt install -qq -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          for i in $(cat builds.openjdk)
          do docker buildx build --squash --push --platform 'linux/amd64,linux/arm64' --builder builder -f ${i}/Dockerfile -t jnix85/activemq:{i} .
          done
  build_alpine_container_images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update -qq
          sudo apt install -qq -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          for i in $(cat builds.alpine)
          do docker buildx build --squash --push --platform 'linux/amd64,linux/arm64' --builder builder -f ${i}/Dockerfile -t jnix85/activemq:{i} .
          done
  
